export const markers = [
  {
    id: 1,
    position: { lat: 1.3, lng: 103.8 },
    status: "congested",
    location: "Orchard Road",
    lastUpdated: "10 mins ago",
    vehiclesDetected: 120,
    carSpeed: "10 km/h",
    action: "Divert traffic, Increase light timing",
    degrees: 0, 
  },
  {
    id: 2,
    position: { lat: 1.34, lng: 103.96 },
    status: "normal",
    location: "East Coast Parkway",
    lastUpdated: "5 mins ago",
    vehiclesDetected: 30,
    carSpeed: "70 km/h",
    degrees: 90, 
  },
  {
    id: 3,
    position: { lat: 1.42, lng: 103.83 },
    status: "congested",
    location: "Woodlands Checkpoint",
    lastUpdated: "15 mins ago",
    vehiclesDetected: 200,
    carSpeed: "5 km/h",
    action: "Notify authorities, Suggest alternative routes",
    degrees: 180, 
  },
  {
    id: 4,
    position: { lat: 1.36, lng: 103.75 },
    status: "normal",
    location: "Jurong East",
    lastUpdated: "8 mins ago",
    vehiclesDetected: 50,
    carSpeed: "60 km/h",
    degrees: 270, 
  },
];
